// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCILypJYEXe8ZVqlp0dNWcb3W8XOCwmFvc',
    appId: '1:148726362822:web:03b2d308df8f582b87ddc7',
    messagingSenderId: '148726362822',
    projectId: 'twttr-cln',
    authDomain: 'twttr-cln.firebaseapp.com',
    storageBucket: 'twttr-cln.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUnUovriRX9t7QEAVWQeU7cDjqSqvHhJI',
    appId: '1:148726362822:android:4f6bf915942b95dd87ddc7',
    messagingSenderId: '148726362822',
    projectId: 'twttr-cln',
    storageBucket: 'twttr-cln.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByLQ-dYKE-BlULSioGvmbx_08pa7-iAbw',
    appId: '1:148726362822:ios:9fa5b71a56af0bd987ddc7',
    messagingSenderId: '148726362822',
    projectId: 'twttr-cln',
    storageBucket: 'twttr-cln.appspot.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByLQ-dYKE-BlULSioGvmbx_08pa7-iAbw',
    appId: '1:148726362822:ios:f4bb73c32bab965187ddc7',
    messagingSenderId: '148726362822',
    projectId: 'twttr-cln',
    storageBucket: 'twttr-cln.appspot.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
