apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: realworld-system

spec:
  selector:
    app: api

  type: ClusterIP

  ports:
  - name: api
    port: 3000
    targetPort: api
  - name: api-debug
    port: 4000
    targetPort: api-debug
  - name: metrics
    port: 3001
    targetPort: metrics
  - name: prometheus
    port: 3002
    targetPort: prometheus
