# The api pod will act as the ops person for initializing Vault and loading
# the RSA private key into vault. This will allow vault to run inside the cluster
# for dev purposes. Initializing Vault has to happen before this service starts.
# Normally Vault would run outside the cluster and already be avalable with the
# RSA private keys we are using.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: realworld-system

spec:
  selector:
    matchLabels:
      app: api
  
  template:
    metadata:
      labels:
        app: api

    spec:
      volumes:
        - name: vault
          persistentVolumeClaim:
            claimName: vault-credentials

      initContainers:

      - name: init-vault-system
        image: service-image
        command: ['./admin', 'vault-init']
        volumeMounts:
          - name: vault
            mountPath: /vault

      - name: init-vault-loadkeys
        image: service-image
        command: ['./admin', 'vault']
