apiVersion: v1
kind: Namespace
metadata:
  name: api-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api-system

spec:
  selector:
    matchLabels:
      app: api

  template:
    metadata:
      labels:
        app: api

    spec:
      terminationGracePeriodSeconds: 60

      initContainers:
      - name: init-migrate
        image: api-image
        command: ['./admin', 'migrate']

      - name: init-seed
        image: api-image
        command: ['./admin', 'seed']

      containers:
      - name: api
        image: api-image

        ports:
        - name: api
          containerPort: 3000
        - name: api-debug
          containerPort: 4000

        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /v1/readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /v1/liveness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        env:
        - name: API_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: db_host
              optional: true

        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

      - name: metrics
        image: metrics-image

        ports:
          - name: metrics
            containerPort: 3001
          - name: prometheus
            containerPort: 3002

        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu

---

apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api-system

spec:
  selector:
    app: api
